stages:
  invalidate:
    cmd: stages/00_invalidate.sh
    deps:
      - stages/00_invalidate.sh
    outs:
      - checksum
  download_data:
    cmd: Rscript stages/01_download.R
    deps:
    - stages/01_download.R
    - checksum
    outs:
    - cache/download
  unzip_data:
    cmd: sh stages/02_unzip.sh
    deps:
    - stages/02_unzip.sh
    - cache/download
    outs:
    - cache/unzip
  build_brick:
    cmd: Rscript stages/03_build.R
    deps:
    - stages/03_build.R
    - cache/unzip
    outs:
    - brick/
  cleanup:
    cmd: sh stages/04_cleanup.sh
    deps:
    - stages/04_cleanup.sh
    - brick/
